### ISSUE TITLE
Downplay HME, sHME and AICM in Model Selection tutorial

### ISSUE THREAD

**Issue by rambaut** [beast-dev/doc#24]
http://beast.community/model_selection_1

Currently has a section on HME, sHME and AICM. This should probably be removed and replaced with a note saying these are not recommended and have be deprecated in Tracer. Perhaps with a link to an explanation?

**Comment by GuyBaele** [comment]
Am not a big fan or simply removing them, as these can still have their use for model selection / averaging studies. But I can reorganize (i.e. move those to the bottom) and clearly indicate that these should be avoided. Let me have a go at this first and then we can re-evaluate.

**Comment by GuyBaele** [comment]
Have moved that section to the bottom of the page and added sufficient warnings. Removed the Tracer info by stating that HME, sHME and AICM will no longer be supported in Tracer due to their poor properties. Only kept the XML specifications.
