### ISSUE TITLE
Tutorial idea: HPMs

### ISSUE THREAD

**Issue by rambaut** [beast-dev/doc#8]
How to collect a bunch of rates from different patients perhaps and estimate using an HPM.

**Comment by plemey** [comment]
The second exercise in the recent version of the rates and dates tutorials does exactly that (for rabies in different bat species).
Just a thought: now that you have implemented covariate loading for GLM-diffusion models, the machinery is there to do the same for fixed effects on rates (or any other parameter that is grouped/linked hierarchically), or for the skygrid with covariates. I realise this imposes additional work, but the data integration aspect seems what can distinguish beastX for the moment...

**Comment by rambaut** [comment]
I will look at extracting that bit into a stand alone tutorial for the website (advanced tutorial). In the section called 'Workshop Tutorials' we can put these longer, multi-section tutorials so we can keep them up-to-date.

**Comment by rambaut** [comment]
Moved your comment about covariate stuff into an Issue for BEAST

**Comment by GuyBaele** [comment]
Most recent version of rates & dates practical that I have is from SISMID last year (i.e. July 2016). Has this been updated and if so, can someone e-mail me the latest version?

**Comment by GuyBaele** [comment]
Question: upon creating HPMs in BEAUti, the corresponding operators on the HPM parameters (i.e. normalNormalMeanGibbsOperator and normalGammaPrecisionGibbsOperator) do not appear in the Operators panel and hence their weights cannot be modified in BEAUti. Would it make more sense to have these operators appear there? Or should I write something in the tutorial indicating that this can be done in the XML?

**Comment by rambaut** [comment]
Add this as an issue in Beauti?
