### ISSUE TITLE
Tutorial idea: Estimating Tipdates.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/doc#9]

**Comment by GuyBaele** [comment]
I think I have a teaching tutorial from Philippe Bioinformatics course at the KU Leuven, where we provide information on how to estimate the sampling dates for one or more taxa (I think I applied it to HIV-1 data from Mike Worobey, estimating the dates of the 1959 and 1960 sequences). Want me to adapt it into an online tutorial?

**Comment by rambaut** [comment]
That would be great. I will add a bit about specifying uncertainty in dates using date ‘precision’

A

**Comment by plemey** [comment]
The WNV continuous phylogeography tutorial also uses precision for dates

**Comment by GuyBaele** [comment]
That WNV tutorial contains the sentence: 'Enter ‘1.0’ as the precision value for 1 year. This will instruct BEAST to add a half year to those sampling dates and construct a uniform window of 1 year around this new value.'

I don't see that half a year being added to the sampling dates in BEAUti, nor in the XML file being generated. Is this something implicit when parsing the XML, i.e. when the precision attribute is there, then half a year is added to the sampling date? If so, we should make this more clear.

**Comment by GuyBaele** [comment]
Tutorial is on line.
